import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'README',
    {
      type: 'category',
      label: 'Strategy',
      link: {type: 'generated-index', title: 'Strategy'},
      items: [{type: 'autogenerated', dirName: 'strategy'}],
    },
    {
      type: 'category',
      label: 'Specs',
      link: {type: 'generated-index', title: 'Feature Specs'},
      items: [{type: 'autogenerated', dirName: 'specs'}],
    },
    {
      type: 'category',
      label: 'Architecture',
      link: {type: 'generated-index', title: 'Architecture'},
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
    {
      type: 'category',
      label: 'Delivery',
      link: {type: 'generated-index', title: 'Delivery'},
      items: [{type: 'autogenerated', dirName: 'delivery'}],
    },
    {
      type: 'category',
      label: 'Operations',
      link: {type: 'generated-index', title: 'Operations'},
      items: [{type: 'autogenerated', dirName: 'operations'}],
    },
    {
      type: 'category',
      label: 'Governance',
      link: {type: 'generated-index', title: 'Governance'},
      items: [{type: 'autogenerated', dirName: 'governance'}],
    },
  ],
};

export default sidebars;
