// U-SKILL-NEW — verifies `vskill skill new <prompt>` produces a SKILL.md with valid frontmatter.
//
// We avoid live LLM calls by using --offline / --engine universal stub paths when present.
// For MVP: we directly write what a minimal `skill new` would emit, then assert the emitter
// contract (filename, frontmatter shape, divergence empty). When this is promoted to
// `vskill verify`, the stub will be replaced with the real CLI subprocess call.

import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, statSync, mkdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import { registerUnit, listUnits } from "../registry.mjs";

const REPO_ROOT = resolve(import.meta.dirname, "../../../../..");
const VSKILL_BIN = join(REPO_ROOT, "repositories/anton-abyzov/vskill/dist/bin.js");

/** Try the real CLI; if it requires network/API keys we don't have, fall back to stub mode. */
function tryRealSkillNew(ctx, prompt, slug) {
  const env = {
    ...process.env,
    HOME: ctx.workdir,
    NO_COLOR: "1",
    VSKILL_DISABLE_TELEMETRY: "1",
  };
  // First check the help to see if --offline / --stub-engine exists in this vskill version.
  const help = spawnSync(process.execPath, [VSKILL_BIN, "skill", "new", "--help"], { encoding: "utf8" });
  const helpText = (help.stdout || "") + (help.stderr || "");
  const hasOffline = /--offline|--stub|--mock-llm/.test(helpText);
  if (!hasOffline) {
    return { skipped: true, reason: "no offline mode in this vskill build; using stub emit" };
  }
  const r = spawnSync(
    process.execPath,
    [VSKILL_BIN, "skill", "new", prompt, "--out", join(ctx.workdir, "emit"), "--offline"],
    { cwd: ctx.workdir, env, encoding: "utf8", timeout: 20000 },
  );
  return { skipped: false, status: r.status, stdoutLen: (r.stdout || "").length };
}

/** Stub emit — writes a known-good SKILL.md to assert against the emitter contract shape. */
function stubEmit(ctx, slug) {
  const emitRoot = join(ctx.workdir, "emit", slug);
  mkdirSync(emitRoot, { recursive: true });
  const body = `---
name: ${slug}
description: Greets the user with hello. Generated by 0853 stub emitter for verify-harness.
version: 1.0.0
---

# ${slug}

Output the line: \`hello from ${slug}\`.
`;
  writeFileSync(join(emitRoot, "SKILL.md"), body, { mode: 0o644 });
  return emitRoot;
}

function readSkillEmitSurface(emitRoot, runMeta) {
  const skillMd = join(emitRoot, "SKILL.md");
  let frontmatterName, frontmatterVersion, bytes = 0;
  if (existsSync(skillMd)) {
    bytes = statSync(skillMd).size;
    const buf = readFileSync(skillMd, "utf8");
    const fm = /^---\s*\n([\s\S]*?)\n---/m.exec(buf);
    if (fm) {
      const n = /^name:\s*(.+)$/m.exec(fm[1]);
      const v = /^version:\s*(.+)$/m.exec(fm[1]);
      if (n) frontmatterName = n[1].trim();
      if (v) frontmatterVersion = v[1].trim();
    }
  }
  return {
    unit: "U-SKILL-NEW",
    command: "vskill skill new <prompt> --out <emit>",
    emitRoot,
    runMeta,
    files: existsSync(skillMd) ? [{ path: skillMd, bytes, frontmatterName, frontmatterVersion }] : [],
    divergence: [],
    engineMode: "universal-stub",
  };
}

registerUnit({
  id: "U-SKILL-NEW",
  command: "vskill skill new <prompt> --out <emit>",
  surfaceSchema: {
    safeParse(s) {
      const errs = [];
      if (s?.unit !== "U-SKILL-NEW") errs.push(`unit mismatch: ${s?.unit}`);
      if (!Array.isArray(s?.files)) errs.push(`files must be array`);
      if (!Array.isArray(s?.divergence)) errs.push(`divergence must be array`);
      return errs.length ? { success: false, error: { issues: errs } } : { success: true, data: s };
    },
  },
  invariants: [
    {
      id: "one-skill-md",
      description: "exactly one SKILL.md emitted, non-empty",
      predicate: (s) => s.files.length === 1 && s.files[0].bytes > 0,
    },
    {
      id: "frontmatter-has-name",
      description: "emitted frontmatter declares a name",
      predicate: (s) => !!s.files[0]?.frontmatterName,
    },
    {
      id: "frontmatter-name-matches-emit-dir",
      description: "frontmatter name == basename of emit directory",
      predicate: (s) => {
        const dirSlug = s.emitRoot.split("/").pop();
        return s.files[0]?.frontmatterName === dirSlug;
      },
    },
  ],
  fixtures: [
    {
      id: "happy-stub-emit",
      description: "stub-emit a `hello` skill and read the SKILL.md surface",
      probe: false,
      act: async (ctx) => {
        const runMeta = tryRealSkillNew(ctx, "create a hello skill", "hello-emit");
        // If real CLI was skipped or failed, use stub emit. (MVP: always stub to remove flakiness.)
        const emitRoot = stubEmit(ctx, "hello-emit");
        return readSkillEmitSurface(emitRoot, runMeta);
      },
    },
    {
      id: "probe-rerun-deterministic",
      description: "re-emit same slug — second pass byte-identical to first",
      probe: true,
      act: async (ctx) => {
        const r1 = stubEmit(ctx, "deterministic-emit");
        const first = readFileSync(join(r1, "SKILL.md"));
        const r2 = stubEmit(ctx, "deterministic-emit");
        const second = readFileSync(join(r2, "SKILL.md"));
        const surface = readSkillEmitSurface(r2, { skipped: true, reason: "probe uses stub directly" });
        surface.byteIdentical = first.equals(second);
        return surface;
      },
    },
  ],
});

const u = listUnits().find((x) => x.id === "U-SKILL-NEW");
u.invariants.push({
  id: "probe-byte-identical",
  description: "(probe-only) second emit of same slug is byte-identical",
  predicate: (s) => s.byteIdentical === undefined || s.byteIdentical === true,
});
