/**
 * Auto-generated sidebar for documentation
 * Generated: 2026-02-22T04:31:22.323Z
 * Uses Docusaurus autogenerated sidebar for reliability with large doc sets
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

module.exports = sidebars;
